// FailedBreak01GC.cs
//
// Auto-generated wrapper for dashboard preset "Failed Break 01 GC".
// Strategy ID: failed_break_v1
//
// Thin subclass of PresetStrategy — every line of trading logic lives in
// PresetStrategy + the AddOns/Preset* engine. This file only registers a
// distinct selectable Strategy in NT8's Strategy Analyzer dropdown and
// hardcodes the ConfigPath default to this preset's JSON file.
//
// To regenerate: re-run the dashboard's "TO NT8" button or
// new-strategy.sh with the updated preset JSON.

#region Using declarations
using System;
using System.IO;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Strategies;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class FailedBreak01GC : PresetStrategy
    {
        // Resolves to {UserDataDir}/bin/Custom/presets/FailedBreak01GC.json on the VM,
        // which is where deploy-nt8.sh mirrors the local presets/ folder.
        protected override string DefaultConfigPath()
            => Path.Combine(NinjaTrader.Core.Globals.UserDataDir,
                            "bin", "Custom", "presets", "FailedBreak01GC.json");

        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name        = "FailedBreak01GC";
                Description = "Dashboard preset \"Failed Break 01 GC\" — auto-generated by /api/convert-to-nt8.";
            }
        }
    }
}
