/**
 * API route: POST /api/convert-to-nt8
 *
 * Server-side endpoint that takes a dashboard preset (sent as JSON in the
 * request body) and writes the two artifacts NT8 needs to register it as a
 * standalone selectable strategy:
 *
 *   1. ninjatrader/strategies/presets/<ClassName>.json
 *      — the preset config that PresetLoader.cs will deserialize at
 *        State.DataLoaded.
 *
 *   2. ninjatrader/strategies/<ClassName>.cs
 *      — a thin C# subclass of PresetStrategy that points DefaultConfigPath()
 *        at the JSON file so the strategy shows up in NT8's Strategy Analyzer
 *        dropdown without the user needing to type a path at configure time.
 *
 * After the route succeeds, the user still needs to:
 *   - Run `cd ninjatrader && ./deploy-nt8.sh` to mirror the files into the
 *     Parallels shared folder NT8 reads from.
 *   - Press F5 in NT8's NinjaScript Editor to compile.
 *
 * The response includes those next steps so the dashboard UI can surface
 * them after the click.
 *
 * This only works in local dev — there's no auth and the file paths are
 * resolved relative to the project root via process.cwd(). That's intentional:
 * the dashboard runs on the user's Mac alongside the project tree, and the
 * whole point is to skip the manual file-shuffling step.
 */

import { NextRequest, NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";
import { exec } from "child_process";
import { promisify } from "util";

const execAsync = promisify(exec);

// Same required-fields list as new-strategy.sh — must match the C#
// PresetLoader.cs deserializer's expectations. Keep these in sync.
const REQUIRED_FIELDS = ["name", "strategyId", "rules", "filters", "params"];

/** Sanitize a preset's `name` into a valid C# identifier — the same logic
 *  new-strategy.sh uses, kept identical so manually-run shell commands and
 *  one-click flows produce the same artifacts. */
function deriveClassName(presetName: string, override?: string): string {
  if (override && /^[A-Za-z_][A-Za-z0-9_]*$/.test(override)) return override;
  // Strip everything that isn't a letter, digit, or underscore.
  let name = presetName.replace(/[^A-Za-z0-9_]/g, "");
  // C# identifiers can't start with a digit — prepend a "Strategy" prefix
  // for the rare preset name that begins with a number.
  if (/^\d/.test(name)) name = `Strategy${name}`;
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    throw new Error(
      `Could not derive a valid C# class name from preset "${presetName}". Pass classNameOverride.`
    );
  }
  return name;
}

/** Generate the C# wrapper file body. Keep the template byte-for-byte
 *  identical to new-strategy.sh's output so a preset converted via either
 *  path produces the same on-disk artifacts. */
function renderWrapper(
  className: string,
  presetFilename: string,
  presetName: string,
  strategyId: string
): string {
  return `// ${className}.cs
//
// Auto-generated wrapper for dashboard preset "${presetName}".
// Strategy ID: ${strategyId}
//
// Thin subclass of PresetStrategy — every line of trading logic lives in
// PresetStrategy + the AddOns/Preset* engine. This file only registers a
// distinct selectable Strategy in NT8's Strategy Analyzer dropdown and
// hardcodes the ConfigPath default to this preset's JSON file.
//
// To regenerate: re-run the dashboard's "TO NT8" button or
// new-strategy.sh with the updated preset JSON.

#region Using declarations
using System;
using System.IO;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Strategies;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class ${className} : PresetStrategy
    {
        // Resolves to {UserDataDir}/bin/Custom/presets/${presetFilename} on the VM,
        // which is where deploy-nt8.sh mirrors the local presets/ folder.
        protected override string DefaultConfigPath()
            => Path.Combine(NinjaTrader.Core.Globals.UserDataDir,
                            "bin", "Custom", "presets", "${presetFilename}");

        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name        = "${className}";
                Description = "Dashboard preset \\"${presetName.replace(/"/g, '\\"')}\\" — auto-generated by /api/convert-to-nt8.";
            }
        }
    }
}
`;
}

export async function POST(req: NextRequest) {
  let body: {
    preset?: Record<string, unknown>;
    classNameOverride?: string;
    deploy?: boolean;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const preset = body.preset;
  if (!preset || typeof preset !== "object") {
    return NextResponse.json({ error: "Missing preset in body" }, { status: 400 });
  }

  // Validate the preset has every field PresetLoader.cs reads. Better to
  // fail loudly here than to write a half-baked file that NT8 silently
  // refuses at State.DataLoaded.
  for (const field of REQUIRED_FIELDS) {
    if (!(field in preset)) {
      return NextResponse.json(
        { error: `Preset is missing required field: ${field}` },
        { status: 400 }
      );
    }
  }

  let className: string;
  try {
    className = deriveClassName(
      String(preset.name ?? ""),
      body.classNameOverride
    );
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Class name error" },
      { status: 400 }
    );
  }

  // process.cwd() is the project root in `next dev` / `next start`. The
  // ninjatrader/ folder lives at the repo root, so paths resolve cleanly
  // without any environment-specific knobs.
  const repoRoot = process.cwd();
  const presetsDir = path.join(repoRoot, "ninjatrader", "strategies", "presets");
  const strategiesDir = path.join(repoRoot, "ninjatrader", "strategies");
  const presetFilename = `${className}.json`;
  const presetPath = path.join(presetsDir, presetFilename);
  const csPath = path.join(strategiesDir, `${className}.cs`);

  try {
    await fs.mkdir(presetsDir, { recursive: true });
    await fs.writeFile(presetPath, JSON.stringify(preset, null, 2), "utf-8");
    await fs.writeFile(
      csPath,
      renderWrapper(
        className,
        presetFilename,
        String(preset.name ?? ""),
        String(preset.strategyId ?? "")
      ),
      "utf-8"
    );
  } catch (e) {
    return NextResponse.json(
      {
        error: `Failed to write strategy files: ${
          e instanceof Error ? e.message : String(e)
        }`,
      },
      { status: 500 }
    );
  }

  // Optional auto-deploy step. Off by default — deploying takes a couple
  // seconds and the user might want to batch multiple preset conversions
  // before pushing to the VM. When opted in, run deploy-nt8.sh and bubble
  // up its stdout/stderr so the UI can surface any rsync issues.
  let deployOutput: string | null = null;
  let deployError: string | null = null;
  if (body.deploy) {
    try {
      const { stdout, stderr } = await execAsync(
        "./deploy-nt8.sh",
        { cwd: path.join(repoRoot, "ninjatrader") }
      );
      deployOutput = stdout + (stderr ? `\n${stderr}` : "");
    } catch (e) {
      deployError = e instanceof Error ? e.message : String(e);
    }
  }

  return NextResponse.json({
    success: true,
    className,
    presetPath,
    csPath,
    deployed: body.deploy === true && deployError === null,
    deployOutput,
    deployError,
    nextSteps: body.deploy
      ? deployError
        ? [
            "Deploy failed — check deployError. Run `cd ninjatrader && ./deploy-nt8.sh` manually.",
            "Press F5 in NT8 NinjaScript Editor to compile.",
            `Pick "${className}" in NT8 Strategy Analyzer.`,
          ]
        : [
            "Press F5 in NT8 NinjaScript Editor to compile.",
            `Pick "${className}" in NT8 Strategy Analyzer.`,
          ]
      : [
          "Run `cd ninjatrader && ./deploy-nt8.sh`",
          "Press F5 in NT8 NinjaScript Editor to compile.",
          `Pick "${className}" in NT8 Strategy Analyzer.`,
        ],
  });
}
