#!/bin/bash
# new-strategy.sh — Convert a dashboard preset JSON into a deployable
# NT8 strategy with one command.
#
# Inputs:
#   $1 = path to the preset JSON file (downloaded from the dashboard's
#        Backtest Presets panel via the Export button)
#   $2 = optional class name override (default: derived from JSON `name`)
#
# What it does:
#   1. Validates the JSON parses + has the fields PresetLoader expects.
#   2. Copies the JSON into ninjatrader/strategies/presets/ with a
#      sanitized filename matching the class name.
#   3. Generates a thin C# wrapper subclass of PresetStrategy at
#      ninjatrader/strategies/<ClassName>.cs.
#   4. Prints the next steps (deploy + F5).
#
# After the script runs, the user just needs to:
#   - cd ninjatrader && ./deploy-nt8.sh
#   - F5 in NT8 NinjaScript Editor to compile
#   - Pick the new strategy in Strategy Analyzer
#
# This file is intentionally idempotent — re-running with the same JSON
# overwrites both the preset file and the wrapper; no clean-up needed.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PRESETS_DIR="$SCRIPT_DIR/strategies/presets"
STRATEGIES_DIR="$SCRIPT_DIR/strategies"

if [ -z "$1" ]; then
  echo "Usage: $0 <preset.json> [ClassName]"
  echo ""
  echo "Example:"
  echo "  $0 ~/Downloads/my_preset.json"
  echo "  $0 ~/Downloads/my_preset.json NQMyStrategy"
  exit 1
fi

PRESET_PATH="$1"
CLASS_NAME_OVERRIDE="$2"

if [ ! -f "$PRESET_PATH" ]; then
  echo "Error: preset file not found: $PRESET_PATH"
  exit 1
fi

# Validate JSON parses and has the fields PresetLoader.cs reads.
if ! command -v jq &> /dev/null; then
  echo "Error: jq is required (brew install jq)"
  exit 1
fi

if ! jq empty "$PRESET_PATH" 2>/dev/null; then
  echo "Error: $PRESET_PATH is not valid JSON"
  exit 1
fi

# Required fields — match PresetLoader.cs's expectations.
for field in name strategyId rules filters params; do
  if [ "$(jq "has(\"$field\")" "$PRESET_PATH")" != "true" ]; then
    echo "Error: preset is missing required field: $field"
    exit 1
  fi
done

PRESET_NAME=$(jq -r '.name' "$PRESET_PATH")
STRATEGY_ID=$(jq -r '.strategyId' "$PRESET_PATH")

# Derive a class name. Strip non-alphanumeric, ensure starts with letter.
if [ -n "$CLASS_NAME_OVERRIDE" ]; then
  CLASS_NAME="$CLASS_NAME_OVERRIDE"
else
  CLASS_NAME=$(echo "$PRESET_NAME" | sed -E 's/[^a-zA-Z0-9]//g')
  # Ensure it starts with a letter — prepend "Strategy" if it starts with a digit.
  if [[ "$CLASS_NAME" =~ ^[0-9] ]]; then
    CLASS_NAME="Strategy${CLASS_NAME}"
  fi
fi

# Validate class name is C#-safe.
if [[ ! "$CLASS_NAME" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
  echo "Error: class name '$CLASS_NAME' is not a valid C# identifier"
  exit 1
fi

# Filename for the preset JSON in presets/. Mirror the class name so
# DefaultConfigPath() is unambiguous.
PRESET_FILENAME="${CLASS_NAME}.json"
PRESET_DEST="$PRESETS_DIR/$PRESET_FILENAME"

# Filename for the C# wrapper.
CS_PATH="$STRATEGIES_DIR/${CLASS_NAME}.cs"

mkdir -p "$PRESETS_DIR"

# Copy preset JSON.
cp "$PRESET_PATH" "$PRESET_DEST"
echo "✓ Copied preset to: $PRESET_DEST"

# Generate C# wrapper from template. Heredoc keeps it readable.
cat > "$CS_PATH" <<EOF
// ${CLASS_NAME}.cs
//
// Auto-generated wrapper for dashboard preset "$PRESET_NAME".
// Strategy ID: $STRATEGY_ID
//
// Thin subclass of PresetStrategy — every line of trading logic lives in
// PresetStrategy + the AddOns/Preset* engine. This file only registers a
// distinct selectable Strategy in NT8's Strategy Analyzer dropdown and
// hardcodes the ConfigPath default to this preset's JSON file.
//
// To regenerate: re-run new-strategy.sh with the updated preset JSON.

#region Using declarations
using System;
using System.IO;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Strategies;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class ${CLASS_NAME} : PresetStrategy
    {
        // Resolves to {UserDataDir}/bin/Custom/presets/${PRESET_FILENAME} on the VM,
        // which is where deploy-nt8.sh mirrors the local presets/ folder.
        protected override string DefaultConfigPath()
            => Path.Combine(NinjaTrader.Core.Globals.UserDataDir,
                            "bin", "Custom", "presets", "${PRESET_FILENAME}");

        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name        = "${CLASS_NAME}";
                Description = "Dashboard preset \"${PRESET_NAME}\" — auto-generated by new-strategy.sh.";
            }
        }
    }
}
EOF

echo "✓ Generated wrapper:    $CS_PATH"
echo ""
echo "Next steps:"
echo "  1. cd $SCRIPT_DIR && ./deploy-nt8.sh"
echo "  2. Press F5 in NT8 NinjaScript Editor to compile"
echo "  3. Pick \"${CLASS_NAME}\" in NT8 Strategy Analyzer"
